#!/bin/bash
# 2015 David Martinka
# This is a utility to save a list of top-level packages from a running system
# with the intention of using this list to clone or backup a system.
# Back up a user's home directory and you would have a near identical system.
# Run with no agruments to create lsit file, run with "-i [filename] where
# filename is a list of packages to install.

ARGS=""

if [ -z "$1" ];	then
	echo "creating top-level package list!"
	STAMP=$(date +%F_%H%M%S)
	sudo aptitude --disable-columns -F '%p' search '~i!~M!~R(~i)' > packages_$HOSTNAME\_$STAMP.lst
else
	if [ "$1" = "-i"  ]; then
		echo
		echo "Reading package list from file..."
		while read i; do
			ARGS="$ARGS $i"
		done < "$2"
		echo "We will install the following packages:"
		echo
		echo "$ARGS"
		echo
                read -p "Proceed with installation? " -n 1 -r
		echo
		if  [[ $REPLY =~ ^[Yy]$ ]]; then
			sudo aptitude install $ARGS
		fi
	else
		echo "derp!"
	fi
fi
